### ISSUE TITLE
Using params or options with ES6

### ISSUE THREAD

**Issue by charlesdsmith** [binaryminds/react-native-sse#10]
Hey I really like this package, only problem is that I'm trying to send a parameter on connection to the server. I an do this if I include the params in the URL, however it doesn't work if I just include an `options` object as an arg with the `EventSource` function. You guys seem to be using typescript to do that. How can I achieve the same in NodeJS? 

Thank you

**Comment by wojciechkrol** [comment]
Hey, what parameter you try to send?
