### ISSUE TITLE
EventSource doesn't close with the server

### ISSUE THREAD

**Issue by kajetanjasztal** [binaryminds/react-native-sse#21]
EventSource doesn't close when the server closes the connection.
Neither on error nor when the stream is terminated.
 
On the web counterpart of my app we're using [`@microsoft/fetch-event-source`](https://www.npmjs.com/package/@microsoft/fetch-event-source) and this other library handles closing the connection correctly in every case.
When accessed with `curl` also terminates as expected.
 
Unfortunately `react-native-sse` doesn't, and it re-fetches the source in a loop, both messages and errors.
As a workaround we were sending custom message to `close()` the stream from the mobile app codebase, but that's not the actual solution and it's getting more and more complicated in a long run.

I would love to get rid of sections commented bellow.
Is this a bug or is there something I'm missing here, so I can make it work as expected?

``` js
const getAnswer = (question) => {
  const eventSource = new EventSource(`${BACKEND_URL}/stream/`, {
    method: "POST",
    headers: {
      Accept: "text/event-stream",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ question }),
  });

  eventSource.addEventListener("open", () => {
    setReceiving(true);
  });

  /** this is not executed when server closes connection,
  /* we need to force it with `eventSource.close()`.
  /* We're also removing event listeners to prevent looping. */
  eventSource.addEventListener("close", () => {
    setReceiving(false);
    // eventSource.removeAllEventListeners();
  });

  /** handling custom message to close connection */
  eventSource.addEventListener("message", (message) => {
    // if (isClosingEvent(message)) {
    //   eventSource.close();
    //   return;
    // }
    handleMessage(message);
  });

  /** this is not a main issue, stream might remain open after sending `error` event */
  eventSource.addEventListener("error", (err) => {
    handleException(err);
    // eventSource.close();
  });
};
```

version: `1.1.0`

**Comment by vpolizzi** [comment]
Same here. We had to put together the same workaround.

**Comment by lucky-009** [comment]
Line 100 of the source code EventSource.js，Even if the state has changed to Done, still go _pollAgain，may cause this problem so,i think remove this code

**Comment by nghiatv** [comment]
set `options.pollingInterval = 0` may be fix your issue
