### ISSUE TITLE
`pollingInterval: 0` overriden by retry from server

### ISSUE THREAD

**Issue by andgrankin** [binaryminds/react-native-sse#30]
In my case I want to execute query once and set option `pollingInterval: 0`. But if server send retry in response, then this option overrides by value from server.  
Expected behaviour is to keep  `pollingInterval: 0`.

**Comment by EmilJunker** [comment]
Please verify that you are using react-native-sse version `1.2.0`. Only this latest version supports `pollingInterval: 0`.

Also, what do you mean by "if server send retry in response"? Are you referring to a specific response status code or header?

**Comment by wojciechkrol** [comment]
@andgrankin Server should not send `retry:` when not needed. This directive should always take priority over pollingInterval.
