### ISSUE TITLE
The events don't trigger it only gives debug output and the message events when the connection to server closes 

### ISSUE THREAD

**Issue by deepak-coding-art** [binaryminds/react-native-sse#36]
```jsx
useEffect(() => {
    if (!authToken) return;
    const url = "http://192.168.1.200:8000" + "/api/ai/sse-test";
    const options = {
      Connection: "keep-alive",
      Authorization: `Bearer ${authToken}`,
      "Content-Type": "application/json",
    };
    const payload = {
      query: "i fee",
    };
    console.log("trigger 0");

    const es = new RNEventSource(url, {
      method: "POST",
      headers: options,
      body: JSON.stringify(payload),
      timeout: 1000,
      timeoutBeforeConnection: 0,
      debug: true,
      pollingInterval: 0,
      withCredentials: true,
    });

    es.addEventListener("message", (event) => {
      const message = JSON.parse(event.data).message;
      console.log("SSE Event:", message);
    });

    es.addEventListener("error", (error) => {
      console.error("SSE Error:", error);
    });

    es.addEventListener("open", () => {
      console.log("SSE Connection opened");
      setResponseText("");
    });

    es.addEventListener("close", () => {
      console.log("SSE Connection closed");
    });

    return () => {
      es.removeAllEventListeners();
      es.close();
    };
  }, [authToken]);
```

## Output:
```bash
 LOG  trigger 0
 DEBUG  [EventSource] Will open new connection in 0 ms.
 DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  SSE Connection opened
 ERROR  [ReferenceError: Property 'setResponseText' doesn't exist]
 DEBUG  [EventSource][onreadystatechange] ReadyState: DONE(4), status: 200
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 LOG  SSE Event: This is a SSE message
 DEBUG  [EventSource][onreadystatechange][DONE] Operation done.
```

It stops unstill the server closes connection

**Comment by EmilJunker** [comment]
`react-native-sse` can only trigger events when the underlying xhr object's `onreadystatechange` handler is called. It looks like this doesn't happen with your SSE connection. That's why you only see log output once initially (on open) and then again at the end (on close).

**Comment by EmilJunker** [comment]
There was a similar issue raised in #26. According to that, the problem could be related to the infamous Flipper bug.

A solution to the Flipper problem is described here: https://stackoverflow.com/questions/69235694/react-native-cant-connect-to-sse-in-android/69235695#answer-69235695

**Comment by deepak-coding-art** [comment]
I think this can be the bug i am using expo can you please point recourse to solve this in expo

**Comment by EmilJunker** [comment]
I don't know how to solve this problem in expo. I think the workaround only works if you build locally.

However, the Flipper issue only affects debug builds. If you build a release version, everything should work normally.

**Comment by BuddhaBing** [comment]
I have this same issue on iOS (which shouldn't be affected by the Flipper issue) and in both debug and release builds (which again shouldn't be affected by the Flipper issue)

**Comment by wojciechkrol** [comment]
Hello,

I have tested it on an iOS device using both the Mercure demo and Postman Echo, and it works as expected on my end:

```
=== POSTMAN-ECHO ===
 DEBUG  [EventSource] Will open new connection in 500 ms.
 DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:15.794Z Open SSE connection.
 DEBUG  [EventSource][onreadystatechange][OPEN] Connection opened.
 LOG  2023-12-16T12:16:15.801Z message {"data": "Message at time 2023-12-15T19:32:28+00:00", "lastEventId": "1", "type": "message", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:17.165Z error {"data": "Error encountered while processing event", "lastEventId": "2", "type": "error", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:18.268Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "3", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:19.291Z notification {"data": "Update request received", "lastEventId": "4", "type": "notification", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:20.315Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "5", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:21.359Z error {"data": "Error encountered while processing event", "lastEventId": "6", "type": "error", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:22.468Z info {"data": "Keep listening to server updates", "lastEventId": "7", "type": "info", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:23.490Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "8", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:24.503Z info {"data": "Keep listening to server updates", "lastEventId": "9", "type": "info", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:16:25.644Z info {"data": "Keep listening to server updates", "lastEventId": "10", "type": "info", "url": "https://postman-echo.com/server-events/10"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: DONE(4), status: 200
 DEBUG  [EventSource][onreadystatechange][DONE] Operation done.

=== MERCURE ===
 DEBUG  [EventSource] Will open new connection in 500 ms.
 DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:28:32.870Z Open SSE connection.
 DEBUG  [EventSource][onreadystatechange][OPEN] Connection opened.
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:28:40.042Z message {"data": "{
\"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
\"availability\": \"https://schema.org/OutOfStock\"
}", "lastEventId": "#1702729720137-0", "type": "message", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:28:48.124Z ping {"data": "{
\"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
\"availability\": \"https://schema.org/OutOfStock\"
}", "lastEventId": "#1702729728223-0", "type": "ping", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:28:52.668Z notification {"data": "{
\"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
\"availability\": \"https://schema.org/OutOfStock\"
}", "lastEventId": "#1702729732767-0", "type": "notification", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
 DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
 LOG  2023-12-16T12:28:56.112Z info {"data": "{
\"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
\"availability\": \"https://schema.org/OutOfStock\"
}", "lastEventId": "#1702729736208-0", "type": "info", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
```

Tested using Expo Go and Expo Dev Client.
```
"expo": "~49.0.15",
"react-native": "0.72.6",
"react-native-sse": "^1.2.0",
```

**Comment by datka134** [comment]
> I think this can be the bug i am using expo can you please point recourse to solve this in expo

try to delete flipper , it work for me atleast

**Comment by abayomi185** [comment]
> Hello,
> 
> I have tested it on an iOS device using both the Mercure demo and Postman Echo, and it works as expected on my end:
> 
> ```
> === POSTMAN-ECHO ===
>  DEBUG  [EventSource] Will open new connection in 500 ms.
>  DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:15.794Z Open SSE connection.
>  DEBUG  [EventSource][onreadystatechange][OPEN] Connection opened.
>  LOG  2023-12-16T12:16:15.801Z message {"data": "Message at time 2023-12-15T19:32:28+00:00", "lastEventId": "1", "type": "message", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:17.165Z error {"data": "Error encountered while processing event", "lastEventId": "2", "type": "error", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:18.268Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "3", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:19.291Z notification {"data": "Update request received", "lastEventId": "4", "type": "notification", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:20.315Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "5", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:21.359Z error {"data": "Error encountered while processing event", "lastEventId": "6", "type": "error", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:22.468Z info {"data": "Keep listening to server updates", "lastEventId": "7", "type": "info", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:23.490Z ping {"data": "Server time is 2023-12-15T19:32:28+00:00", "lastEventId": "8", "type": "ping", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:24.503Z info {"data": "Keep listening to server updates", "lastEventId": "9", "type": "info", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:16:25.644Z info {"data": "Keep listening to server updates", "lastEventId": "10", "type": "info", "url": "https://postman-echo.com/server-events/10"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: DONE(4), status: 200
>  DEBUG  [EventSource][onreadystatechange][DONE] Operation done.
> 
> === MERCURE ===
>  DEBUG  [EventSource] Will open new connection in 500 ms.
>  DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:28:32.870Z Open SSE connection.
>  DEBUG  [EventSource][onreadystatechange][OPEN] Connection opened.
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:28:40.042Z message {"data": "{
> \"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
> \"availability\": \"https://schema.org/OutOfStock\"
> }", "lastEventId": "#1702729720137-0", "type": "message", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:28:48.124Z ping {"data": "{
> \"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
> \"availability\": \"https://schema.org/OutOfStock\"
> }", "lastEventId": "#1702729728223-0", "type": "ping", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:28:52.668Z notification {"data": "{
> \"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
> \"availability\": \"https://schema.org/OutOfStock\"
> }", "lastEventId": "#1702729732767-0", "type": "notification", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  LOG  2023-12-16T12:28:56.112Z info {"data": "{
> \"@id\": \"https://demo.mercure.rocks/.well-known/mercure/ui/demo/books/1.jsonld\",
> \"availability\": \"https://schema.org/OutOfStock\"
> }", "lastEventId": "#1702729736208-0", "type": "info", "url": "https://demo.mercure.rocks/.well-known/mercure?topic=https%3A%2F%2Fexample.com%2Fmy-private-topic"}
> ```
> 
> Tested using Expo Go and Expo Dev Client.
> 
> ```
> "expo": "~49.0.15",
> "react-native": "0.72.6",
> "react-native-sse": "^1.2.0",
> ```

Please can you show the code to reproduce?

**Comment by wojciechkrol** [comment]
@abayomi185:
```typescript
useEffect(() => {
    const es = new EventSource<"ping" | "message" | "info" | "notification">(
      "https://postman-echo.com/server-events/10",
      {
        headers: {
          Connection: "keep-alive",
          "Content-Type": "application/json",
        },
        method: "POST",
        body: JSON.stringify({ foo: "bar" }),
        timeoutBeforeConnection: 0,
        debug: true,
        pollingInterval: 0,
        withCredentials: true,
      }
    );

    es.addEventListener("open", () => {
      console.log(new Date(), "Open SSE connection.");
    });

    es.addEventListener("ping", (event) => {
      console.log(new Date(), "ping", event);
    });

    es.addEventListener("info", (event) => {
      console.log(new Date(), "info", event);
    });

    es.addEventListener("notification", (event) => {
      console.log(new Date(), "notification", event);
    });

    es.addEventListener("error", (event) => {
      console.log(new Date(), "error", event);
    });

    es.addEventListener("message", (event) => {
      console.log(new Date(), "message", event);
    });

    return () => {
      console.log("close");
      es.removeAllEventListeners();
      es.close();
    };
  }, []);
```
