### ISSUE TITLE
only open event triggered

### ISSUE THREAD

**Issue by Judy0406-CJ** [binaryminds/react-native-sse#40]
Follow the example to create eventSource, it is supposed to be pretty straightforward, but only `open` event was triggered, what might be wrong? 

>  DEBUG  [EventSource] Will open new connection in 0 ms.
>  DEBUG  [EventSource][onreadystatechange] ReadyState: HEADERS_RECEIVED(2), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
**>  LOG  EventType: open**
>  DEBUG  [EventSource][onreadystatechange][OPEN] Connection opened.
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: LOADING(3), status: 200
>  DEBUG  [EventSource][onreadystatechange] ReadyState: DONE(4), status: 200
>  DEBUG  [EventSource][onreadystatechange][DONE] Operation done.

**Comment by EmilJunker** [comment]
The logs you posted look good. Each line where it says `ReadyState: LOADING` in the logs is a potential event that could have been triggered, provided that the XHR object's `responseText` is a properly formatted event stream response. The response should look like this when opened in a web browser. (you can also try this link: https://fetch-eventstream.glitch.me/sse)

```
id: 0
event: increment
data: hello from SSE #0

id: 1
event: increment
data: hello from SSE #1

id: 2
event: increment
data: hello from SSE #2

id: 3
event: increment
data: hello from SSE #3
```

**Comment by Judy0406-CJ** [comment]
@EmilJunker Thanks for the reply. You mean the response text has to be this format(include `id`, `event` and `data` in each line)? The streaming API I built is actually returning a customized json in each event, should I wrap it like 

```
id: 1
event: increment
data: {my_customized_json_string}
```

**Comment by EmilJunker** [comment]
Yes, the response text has to be in the above format. I believe the `id` is optional, but `event` and `data` are required. The data can be a JSON string if you want.

**Comment by Judy0406-CJ** [comment]
@EmilJunker 
I tried `https://fetch-eventstream.glitch.me/sse` you posted above, still see the same debug log, but not message event triggered.

I just used the first example code from readme.txt, do you have a code snippet that works with above link?

**Comment by EmilJunker** [comment]
The event name in the link I posted is called `increment`. If you only added an event listener for `message`, you won't receive these events. You need to add this block of code:

```js
es.addEventListener("increment", (event) => {
  console.log(event.data);
});
```

**Comment by Judy0406-CJ** [comment]
@EmilJunker Thank you for guiding me. I was able to understand the SSE protocol and successfully receive the data. 
One more thing is that each time an event is triggered (tried increment and message type), it activates all historical events. For instance, when event1 occurs, the eventListener captures event1. Subsequently, when event2 occurs, the eventListener captures both event1 and event2. This process continues until the final event, capturing all events in the sequence.
Do you have any idea? 

I tested with cURL, it got the same result from my API and above link. Pretty normal event stream.

**Comment by EmilJunker** [comment]
It's hard to tell what the problem is without seeing your API, but what I can say is that it's very important to have a double newline `\n\n` between the events in the response text. Without that, the library won't be able to know where one event ends and the next one begins.

Incorrect:
```
id: 0
event: increment
data: hello from SSE #0
id: 1
event: increment
data: hello from SSE #1
id: 2
event: increment
data: hello from SSE #2 
```

Correct:
```
id: 0
event: increment
data: hello from SSE #0

id: 1
event: increment
data: hello from SSE #1

id: 2
event: increment
data: hello from SSE #2 
```

**Comment by Judy0406-CJ** [comment]
@EmilJunker Thank you so much for pointing me to the right direction. It turned out to be a new line sep issue between server and client. Problem solved.

Thanks again for helping me out, closing the ticket. Appreciate it.
