### ISSUE TITLE
Messages Received Only After Connection is Terminated

### ISSUE THREAD

**Issue by pokaru** [binaryminds/react-native-sse#46]
It was simple enough to install and use the library, however as the title says the messages appear to only make their way to the event listener after I kill the server.

```
clientCodeSnippet() {
    const config = {
        headers: {
            Authorization: {toString: () => "Bearer blahblahblah"}
        }
    }

    const eventSource = new EventSource(url, config);

    eventSource.addEventListener("message", (event) => {
        console.log("event type: ", event.type);
        console.log("event data: ", event.data);
    });
}
```

1.  Start up my client and server.
2. Generate a few messages via curl.
3. Wait for client to log the events.
4. Kill the server.
5. Client logs the events.

This works fine outside of my client code.  In other words if I establish my SSE connection via the command line and run the same test, the messages sent show up in real time.

Any help would be appreciated.

**Comment by EmilJunker** [comment]
This problem is likely caused by Flipper. You need to comment out Flipper to make SSE work in debug builds, see #26.

**Comment by pokaru** [comment]
Or run in release mode.
https://github.com/binaryminds/react-native-sse/issues/26#issuecomment-2002032183
