### ISSUE TITLE
Create a similar library for reactjs

### ISSUE THREAD

**Issue by meirm** [binaryminds/react-native-sse#50]
I took the source code of the eventSource.js and used it in a reactjs app and worked like a charm, so this library is not limited to react-native. 
Great job.

**Comment by EmilJunker** [comment]
Yes, this library is based purely on XMLHttpRequest, so it will work pretty much anywhere. However, EventSource should work out of the box in reactjs, so you shouldn't even need this library there.

**Comment by meirm** [comment]
The eventSource in reactjs doesn't support POST.

**Comment by arpitmalik** [comment]
@meirm You can use https://www.npmjs.com/package/event-source-polyfill

**Comment by meirm** [comment]
You need POST request when you are using services such as OpenAI API in which you post the chat history (which is long) and get the results back as a stream.
